name: Build Eleventy

on:
  push:
    branches:
      - main
env:
  # Setting an environment variable with the value of a configuration variable
  STRAPI_URL: ${{ vars.STRAPI_URL }}
  STRAPI_TOKEN: ${{ vars.STRAPI_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build:prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
